/**
 * List of all registered action types.
 * 
 * @type {Object}
 */
export const types = {
	TOGGLE_BLOCK: 'TOGGLE_BLOCK',
	AUTOCOMPLETE_DEPARTURE_REQUEST: 'AUTOCOMPLETE_DEPARTURE_REQUEST',
	AUTOCOMPLETE_IS_LOADING: 'AUTOCOMPLETE_IS_LOADING',
	AUTOCOMPLETE_IS_LOADED: 'AUTOCOMPLETE_IS_LOADED',
};