/**
 * List of all registered action types.
 * 
 * @type {Object}
 */
export const types = {
	LOAD_CONFIG: 'LOAD_CONFIG',
	
	TOGGLE_BLOCK: 'TOGGLE_BLOCK',
	AUTOCOMPLETE_LOADING_STARTED: 'AUTOCOMPLETE_LOADING_STARTED',
	AUTOCOMPLETE_LOADING_FINISHED: 'AUTOCOMPLETE_LOADING_FINISHED',
	AUTOCOMPLETE_INPUT_VALUE_CHANGED: 'AUTOCOMPLETE_INPUT_VALUE_CHANGED',
	AUTOCOMPLETE_SUGGESTIONS_CHANGED: 'AUTOCOMPLETE_SUGGESTIONS_CHANGED',
	AIRPORT_SELECTED: 'AIRPORT_SELECTED'
};