/**
 * List of all registered action types.
 * 
 * @type {Object}
 */
export const types = {
	LOAD_CONFIG: 'LOAD_CONFIG',
	
	TOGGLE_BLOCK: 'TOGGLE_BLOCK',
	AUTOCOMPLETE_DEPARTURE_REQUEST: 'AUTOCOMPLETE_DEPARTURE_REQUEST',
	AUTOCOMPLETE_LOADING_STARTED: 'AUTOCOMPLETE_LOADING_STARTED',
	AUTOCOMPLETE_LOADING_FINISHED: 'AUTOCOMPLETE_LOADING_FINISHED',
	AUTOCOMPLETE_VALUE_CHANGED: 'AUTOCOMPLETE_VALUE_CHANGED'
};