/**
 * List of all registered action types.
 */
export const LOAD_CONFIG = 'LOAD_CONFIG';
export const TOGGLE_DATEPICKER = 'TOGGLE_DATEPICKER';
export const SET_AVAILABLE_DATES = 'SET_AVAILABLE_DATES';
export const AUTOCOMPLETE_LOADING_STARTED = 'AUTOCOMPLETE_LOADING_STARTED';
export const AUTOCOMPLETE_LOADING_FINISHED = 'AUTOCOMPLETE_LOADING_FINISHED';
export const AUTOCOMPLETE_SUGGESTIONS_CHANGED = 'AUTOCOMPLETE_SUGGESTIONS_CHANGED';
export const AUTOCOMPLETE_PUSH_TO_PREVIOUS = 'AUTOCOMPLETE_PUSH_TO_PREVIOUS';
export const AIRPORT_SELECTED = 'AIRPORT_SELECTED';
export const SELECT_DATE = 'SELECT_DATE';
export const ADD_PASSENGER = 'ADD_PASSENGER';
export const REMOVE_PASSENGER = 'REMOVE_PASSENGER';
export const SET_PASSENGER_COUNTER = 'SET_PASSENGER_COUNTER';
export const SHOW_ERRORS = 'SHOW_ERRORS';
export const SET_CLASS_TYPE = 'SET_CLASS_TYPE';
export const TOGGLE_VICINITY_DATES = 'TOGGLE_VICINITY_DATES';
export const SET_VICINITY_DATES = 'SET_VICINITY_DATES';
export const TOGGLE_DIRECT_FLIGHT = 'TOGGLE_DIRECT_FLIGHT';
export const SET_DIRECT_FLIGHT = 'SET_DIRECT_FLIGHT';
export const CHANGE_COUPON_NUMBER = 'CHANGE_COUPON_NUMBER';
export const CHANGE_MILE_CARD_NUMBER = 'CHANGE_MILE_CARD_NUMBER';
export const CHANGE_MILE_CARD_PASSWORD = 'CHANGE_MILE_CARD_PASSWORD';
export const SET_ROUTE_TYPE = 'SET_ROUTE_TYPE';
export const ADD_SEGMENT = 'ADD_SEGMENT';
export const DELETE_SEGMENT = 'DELETE_SEGMENT';
export const REMOVE_COMPLEX_SEGMENTS = 'REMOVE_COMPLEX_SEGMENTS';
